### ISSUE TITLE
[Feat (only Client)] 아르바이트(Job) View 구성

### ISSUE THREAD

**Issue by 220v-K** [Hey-Porori/iOS_All#2]
### 📝 작업할 내용 요약

아르바이트 모집 기능 측 화면들의 틀을 잡고, 디자인대로 구성합니다.

---

### 🛠️ Tasks

* [x] 알바 메인 화면
* [x] 알바 게시글 상세 화면
* [x] 알바 모집 게시글 작성 화면(1, 2, 3)
* [ ] 내 프로필 조회
* [ ] 지원자 이력서 확인 화면
* [ ] 알바 지원 현황 확인
