### ISSUE TITLE
[Feat (only Client)] 중고거래 측 View 작업 (1)

### ISSUE THREAD

**Issue by 220v-K** [Hey-Porori/iOS_All#21]
### 📝 작업할 내용 요약

중고거래 측 View작업을 할 예정입니다. 아무튼. 네.

---

### 🛠️ Tasks

* [x] 중고거래 메인 화면
* [x] 게시글 조회 화면
* [x] 게시글 작성 화면
* [ ] 채팅 화면 (Optional, 우선순위 후순위)
* [ ] 채팅방 목록 화면 (우선순위 후순위)
