### ISSUE TITLE
[Feat (with Server)] Sign in with Apple 기능 구현

### ISSUE THREAD

**Issue by 220v-K** [Hey-Porori/iOS_All#3]
### 📝 작업할 내용 요약

서버와의 통신을 통한 Sign in with Apple (애플 로그인) 기능을 구현합니다.

---

### 🛠️ Tasks

* [ ] 진입 화면(로그인 화면) 구성
* [x] Sign in with Apple 버튼을 통한 Client 상에서의 데이터 수집
* [x] 수집한 데이터를 바탕으로 한 Server와의 통신
* [x] 반환된 response를 이용한 기기 로그인정보 저장
* [ ] 저장된 로그인 정보를 이용한 자동 로그인 구현 틀 잡기
* [x] Alamofire 패키지 적용

### 참고 이미지
<img src="https://github.com/Hey-Porori/iOS_All/assets/82885362/9990aa66-34dc-44d7-bf9b-8a2011cadde3" width="30%"/>
